### PR TITLE
Show the actual time of the last inform in a tooltip

### PR DESCRIPTION
**Pull request by akcoder**
Simple change, when hovering over the last inform value, you can now see the exact date and time in a tooltip

### CODE REVIEW

**Comment by akcoder** [comment]
I've updated this to convert the date into the local time before formatting. time_zone is set in config/application.rb. If the time_zone is not configured, falls back to UTC

**Comment by zaidka** [comment]
Thanks Dan! You actually don't need a helper method. You can either use:

    device['summary.lastInform'].to_time

to show the time using the server's time zone (I think). Or:

    device['summary.lastInform'].to_time.in_time_zone

to print in the time zone defined in config, or in UTC if that's not defined.

This is simpler and also doesn't hard code the time format allowing you to easily configure a different format.

May I suggest creating a new pull request because this one's getting big for a relatively small change?

**Comment by akcoder** [comment]
Thank you! That is significantly simpler! I have almost no experience in
Ruby/RoR.  I'll get a new PR up in a few minutes.

-dan

**Comment by akcoder** [comment]
This PR should still work. I've rebase/squashed to be just the two files that need to be changed.

**Comment by zaidka** [comment]
I think you missed changing the index page :)

**Comment by akcoder** [comment]
Ack, sorry about that. My IDE was out of sync with my VM. Try now!

**Comment by zaidka** [comment]
Looks great, thanks.

**Pull request merged**
