### PR TITLE
Manage privileges, roles and users in a relational database and in the gui

### PR DESCRIPTION
**Pull request by okraits**
I added models, controllers and a gui to manage privileges, roles and users and store related data in a relational database. Only the admin role has privileges to manage privileges, roles and users.

Switching between using the yml files or using the relational database and the gui is done through a configuration option in *config/application.rb*.

### CODE REVIEW

**Comment by akcoder** [comment]
Why store this in another db? Is there an issue with using Mongo which is
already required?

**Comment by okraits** [comment]
Simplicity. sqlite3 is already a dependency of genieacs-gui, mongodb isn't.
Nevertheless, Improvements are always welcome.

**Comment by akcoder** [comment]
You're right. I somehow missed that this was for the GUI.

On Wed, Mar 23, 2016 at 11:00 PM, Oliver Kraitschy <notifications@github.com

**Comment by zaidka** [comment]
Thanks for the PR, and sorry for all this delay. I haven't looked at it yet, but will definitely do in the coming days.

**Comment by zaidka** [comment]
Great work, thanks! There's a few things I'd like to add. Let me know what you think:

- Remove the existing file based storage of users and roles.

- Now that user accounts are created using a GUI, we can store passwords securely rather than plain text.

- Ability to reset a password in case the admin password is forgotten. 

- Move users and roles tabs out of the way to a special "settings" page.

Will try to implement those some time, but as always pull requests are welcome.

**Comment by okraits** [comment]
I'd vote for all of your points with two comments:

- I don't know if there are users who explicitly want to use the files for managing users and roles. If there are some, then i would at least make db based storage the default.
- Right now, users and roles tabs are at least right-aligned and thus a little separated from the rest so moving them away has low priority for me.

More importantly I'd like to add the possibility to modify privileges - right now you can only delete a privilege and then create a different one.

What about documenting the TODOs somewhere so we can track them and people can look at the roadmap and the status of the various items? I'd vote for creating Github issues and tagging them accordingly.

**Pull request merged**
