### PR TITLE
Creating something like a tree in the box at devices

### PR DESCRIPTION
**Pull request by s-icerna**
There are commets to each function I add.
Just a front end change. If you open any device, it loads and make in the box something like a tree, where you can click on a param and it open the next step contains the clicked step-path-name.

Hope you like the idea! I´m open for more work, if you have some critic. And I´m already working on some new implents.

Regards Igor

### CODE REVIEW

**Comment by zaidka** [comment]
Thanks! I haven't had the chance to look at your PR yet, but I notice you closed it. You intend to make further changes before making another PR?

**Comment by s-icerna** [comment]
No problem, this will be my project for the next months, so they will be
more. i closed it because the way i send the commits was dirty, I am a
newbie in git so, i will make clean commits and send it again.

This PR contains dropdown choose when you add a object to preset, so you
can just choose existing objects. and i made a tree structur at the devices
box. think its better to handle.

2015-12-03 19:34 GMT+01:00 Zaid Abdulla <notifications@github.com>:

**Comment by zaidka** [comment]
Everyone is newbie in git :) I know I am. Thgouh I recently turned "pro" when I discovered this: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

A couple of notes if I may: keep your changes incremental as much as possible. If you must make a drastic change, keep it in a separate branch so we can take our time with it before pushing it to master. Unlike the core, the GUI isn't yet versioned so we need to be careful what goes into master.

Was the parameter search functionality removed as a result of changing representation to a tree structure? I haven't seen your change yet, but perhaps instead of a tree, the search box is made smart by showing auto complete hints that you can just click thereby behaving as a tree that you navigate as well as a flat parameter list that is searchable. What do you think?

**Comment by s-icerna** [comment]
Thanks for the link ;)

No it wasn´t removed, but it works not the same. so lets say you just see
the params from the 2nd step("DeviceInfo.MoreInfo") and the 3rd step would
be ("DeviceInfo.MoreInfo.LastStepforthispath Value") but the 3rd steps is
hidden. If you click on "DeviceInfo.MoreInfo" all lower level items show up.
The search functional shows just the visible items, if you tipe in
"MoreInfo" so you see this item, but not the lower level items. If you
search it and click on it of course the lower level show up. befor
searching you have to know the name of the upper level.

ps: the steps are split with the dot.

2015-12-03 22:23 GMT+01:00 Zaid Abdulla <notifications@github.com>:

**Pull request closed without merging**
