### PR TITLE
Improvements to ping devices

### PR DESCRIPTION
**Pull request by akcoder**
Allow the user to specify the device parameter to use for the ip to ping. Defaults to summary.ip so no impacting changes to users.

Add some error checking around ping. Previously "Device is offline" would be displayed if no ip was passed in, or '(null)' was passed in. I added specific checking for this and display an alert message to the user.

### CODE REVIEW

**Comment by zaidka** [comment]
I think a better solution would be to use the IP/host name extracted from connection request URL parameter. That way it would always work without the need for manual configuration. What do you think?

**Comment by akcoder** [comment]
The backend takes care of the pinging. This makes the front end use the
proper URL, port and scheme for making a connection to the backend.

-dan

**Comment by zaidka** [comment]
Looking at the diff it looks like you've added a new config file (show_parameters.yml). What I meant is instead of using the IP from the parameter determined in that file, why not hard code it to use the IP from ConnectionRequestURL parameter which I imagine should work in all cases anyway.

**Comment by akcoder** [comment]
The reason for that is our CPEs have two IP addresses, one on a private
management network, and the other on the public network (after the CPE has
authenticated via PPPoE). Because the PPPoE connection may not always be
up, for use the reliable way is to ping the summary.managementIp alias.

In our environment, show_parameters.yml is this:
pingIp: summary.managementIp

For my checkin, I set it to pingIp to summary.ip so existing
implementations would continue working with no changes.

-dan

**Comment by zaidka** [comment]
In your particular case the parameter summary.managementIp should match the IP portion in ConnectionRequestURL since connection requests ideally go through the management connection. Can you confirm?

**Comment by akcoder** [comment]
Hmm, you're right :). I'll rework the patch in the next few days.

-dan

**Comment by zaidka** [comment]
Great. Thank you :)

**Comment by akcoder** [comment]
Fixed! This requires a corresponding commit to config/parameters-sample.json (adding  "InternetGatewayDevice.ManagementServer.ConnectionRequestURL": {"alias": "summary.connectionUrl"}, ).

I have to leave for the day and won't be able to sort out my repo issues until tomorrow.

**Comment by zaidka** [comment]
Why not use the following parameters (whichever exists):

    InternetGatewayDevice.ManagementServer.ConnectionRequestURL
    Device.ManagementServer.ConnectionRequestURL

I don't see a benefit in using an alias that's configured in the backend when it can never be anything other than one of these two parameters.

I see you've added a new dependency (ipaddress). This is not necessary; I believe you can extract the host name part from a URL using standard Ruby functions.

**Comment by akcoder** [comment]
Hows this? :)

**Comment by zaidka** [comment]
Sexy! I squashed all the commits into one and replaced the regex with the standard URL parsing function. Thanks.

**Comment by akcoder** [comment]
I didn't even know about that! When I googled "ruby parse IP from string" the options that came up where the ipaddress lib, and regex. The route you choose is much better :).

To quote Jamie Zawinski

> Some people, when confronted with a problem, think "I know, I'll use regular expressions." Now they have two problems.

**Comment by zaidka** [comment]
Hehe. Great quote. Yeah, Ruby standard libraries are pretty comprehensive.

**Pull request closed without merging**
